### PR TITLE
Allow variable overwrite if value cannot be retrieved

### PR DESCRIPTION
**Pull request by rmbl**
Newer serverless versions are preferred here to allow strings as the fallback value (as the test is using).

**Use case for this:**

We're creating a RDS instance on the first deploy and that requires us comment all usages of this plugin that get RDS values. This way we'll still need to deploy twice, but now the values are automatically corrected on the second run.

### CODE REVIEW

**Comment by rmbl** [comment]
Any specific way you're thinking about? Just a config value like `custom.awsResolver.strict` or per resolved variable like `${aws:rds:instance:key!}`?

**Comment by jacob-meacham** [comment]
I think we should start with a global config value, although I'd be open to the latter

**Comment by rmbl** [comment]
I added the configuration value and also updated the README so these changes are reflected in the documentation.

**Comment by jacob-meacham** [comment]
Released these changes as 1.3.0. Thanks for the contribution @rmbl !

**Pull request merged**
